packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - msgpackr-extract

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
