name: ci
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.16.0
          run_install: true
      - name: Typecheck (skip if not set up yet)
        run: pnpm -r -w run typecheck || echo "no typecheck"
      - name: Build API/Frontend/Worker
        run: pnpm -w run build || echo "build not wired yet"
